using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TeamSourceControl_Group4
{
    public class VideoGame
    {
        /// <summary>
        /// ID for each individual game
        ///  ID# is generated by DB
        /// </summary>
        [Key]
        public int GameId { get; set; }

        /// <summary>
        /// The title of the video game
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The rating of the game EX. M, Teen
        /// </summary>
        public string Rating { get; set; }

        /// <summary>
        /// The price of the game
        /// </summary>
        public double Price { get; set; }

        public override string ToString()
        {
            return $"{Title}";
        }
    }
}
